apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:6322
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:6319

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:6320
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: ['container', 'compose_service']
        mappedTags:
          - key: trace_id
            value: trace_id
      tracesToMetrics:
        datasourceUid: prometheus
      serviceMap:
        datasourceUid: prometheus
