global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts/health-alerts.yml

scrape_configs:
  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:6200
          - api:6300

  - job_name: 'tempo'
    metrics_path: /metrics
    static_configs:
      - targets:
          - tempo:6209
          - tempo:6320
