server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:6319/loki/api/v1/push

scrape_configs:
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["com.docker.stack.namespace=my-ads-production"]
    pipeline_stages:
      # drop very old log lines so Loki won't reject them
      - drop:
          older_than: 24h
      # drop anything outside our stack explicitly
      - match:
          selector: '{compose_service!~"^my-ads.*"}'
          action: drop
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container
      - source_labels: ['__meta_docker_container_id']
        target_label: container_id
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: compose_service
      - target_label: job
        replacement: my-ads
