global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:6200

  - job_name: 'tempo'
    metrics_path: /metrics
    static_configs:
      - targets:
          - tempo:6209
